name: Publish Binaries

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        node-version: [18, 19, 20, 21, 22]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix['node-version'] }}

      - name: Install dependencies
        run: npm install

      - name: Build binary
        run: npm run build

      - name: Rename and Upload artifact
        run: |
          ABI_VERSION=$(node -p "process.versions.modules")
          OS_SUFFIX=$([[ ${{ matrix.os }} == 'windows-latest' ]] && echo 'win32-x64' || ([[ ${{ matrix.os }} == 'ubuntu-latest' ]] && echo 'linux-x64' || echo 'darwin-x64'))
          ARCHIVE_NAME="mmap_io-${{ github.ref_name }}-node-v${ABI_VERSION}-${OS_SUFFIX}.tar.gz"
          tar -czvf $ARCHIVE_NAME -C build/binding .
        shell: bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.ref_name }}-node-v${ABI_VERSION}-package
          path: mmap_io-${{ github.ref_name }}-node-v${ABI_VERSION}-${OS_SUFFIX}.tar.gz
