name: Publish Binaries

on:
  push:
    tags: v*

jobs:
  build:
    runs-on: ${{ matrix.build-type.os }}

    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        build-type: [
#          {os: "windows-2019", arch: "amd64"},
#          {os: "ubuntu-22.04", arch: "amd64"},
          {os: "macos-14"}, # Sonoma
          {os: "macos-13"}, # Ventura
        ]
        node-version: [16.14.0, 17.x, 18.x, 19.x, 20.x, 21.x, 22.x, 23.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Enable Corepack
        run: corepack enable

      - name: Set Yarn Version
        env:
          YARN_IGNORE_NODE: 1
        run: yarn set version 1.22.14

      - name: Install Global Dependencies
        run: |
          yarn global add node-gyp

      - name: Install Dependencies
        run: |
          yarn

      - name: Add msbuild to PATH (Windows)
        if: matrix.build-type.os == 'windows-2019'
        uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x64

      - name: Configure node-gyp
        shell: bash
        run: |
          echo '{"cflags_cc": ["-fexceptions"]}' > binding.gyp.json

      - name: Clean build
        run: yarn clean

      - name: Build TypeScript
        run: yarn tsc

      - name: Copy type definitions
        shell: bash
        run: |
          mkdir -p dist
          cp mmap-io.d.ts dist/
          cp dist/mmap-io.d.ts ./

#      - name: Run tests
#        run: |
#          yarn test

      - name: Package binary
        env:
          NODE_PRE_GYP_GITHUB_TOKEN: ${{ secrets.NODE_PRE_GYP_GITHUB_TOKEN }}
        run: yarn package-binary

      - name: Push binary
        env:
          NODE_PRE_GYP_GITHUB_TOKEN: ${{ secrets.NODE_PRE_GYP_GITHUB_TOKEN }}
        run: yarn push-binary