name: Publish Binaries

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-13, macos-latest]
        node-version: [18]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix['node-version'] }}

      - name: Setup Python 3.11 on macOS
        if: runner.os == 'macOS'
        run: |
          python3.11 -m venv venv
          source venv/bin/activate
          python3.11 -m ensurepip --upgrade
        shell: bash

      - name: Install dependencies
        run: npm install

      - name: Build binary
        run: npm run build

      - name: Rename and package artifact
        run: |
          ABI_VERSION=$(node -p "process.versions.modules")
          if [ ${{ matrix.os }} == 'windows-latest' ]; then
            OS_SUFFIX="win32-x64"
          elif [ ${{ matrix.os }} == 'ubuntu-latest' ]; then
            OS_SUFFIX="linux-x64"
          elif [ ${{ matrix.os }} == 'ubuntu-latest' ]; then
            OS_SUFFIX="linux-x64"
          elif [ ${{ matrix.os }} == 'macos-latest' ]; then
            OS_SUFFIX="darwin-arm64"
          else
            OS_SUFFIX="darwin-x64"
          fi
          ARCHIVE_NAME="mmap_io-${{ github.ref_name }}-node-v${ABI_VERSION}-${OS_SUFFIX}.tar.gz"
          tar -czvf $ARCHIVE_NAME -C build/binding .
          echo "ARCHIVE_NAME=${ARCHIVE_NAME}" >> $GITHUB_ENV
        shell: bash

#      - name: Upload artifact
#        uses: actions/upload-artifact@v4
#        with:
#          name: ${{ github.ref_name }}-node-v${ABI_VERSION}-package
#          path: ${{ env.ARCHIVE_NAME }}
#      - name: Release
#        uses: softprops/action-gh-release@v2
#        with:
#          token: ${{ secrets.PUSH_RELEASE_TOKEN }}

      - name: Push binaries
        env:
          NODE_PRE_GYP_GITHUB_TOKEN: ${{ secrets.NODE_PRE_GYP_GITHUB_TOKEN }}
        run: npm run push-binary